AllCops:
  TargetRubyVersion: 2.6.1
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'test/*'

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  ExcludedMethods: ['json.data', 'register', 'schema', 'index', 'show', 'form' ,'describe', 'context', 'before', 'namespace', 'task', 'included', 'params', 'factory', 'define', 'get', 'shared_examples', 'shared_context', 'spec']

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'app/policies/user_access_policy.rb'
    - 'app/policies/employer_access_policy.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Documentation:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - 'lib/tasks/**/*'

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Max: 45

Naming:
  Enabled: false
