---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/comments":
    get:
      summary: List of comments
      tags:
      - Comments
      consumes:
      - application/json
      parameters:
      - name: product
        in: body
        schema:
          type: object
          properties:
            page:
              type: integer
          required: []
      responses:
        '200':
          description: list of products
    post:
      summary: Creates a comment
      tags:
      - Comments
      consumes:
      - application/json
      parameters:
      - name: comment
        in: body
        schema:
          type: object
          properties:
            text:
              type: string
            rate:
              type: integer
            meal_id:
              type: integer
          required:
          - text
          - rate
          - meal_id
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
        '403':
          description: Forbidden
  "/api/v1/meal_categories":
    get:
      summary: List of meal categories
      tags:
      - Meal categories
      consumes:
      - application/json
      parameters:
      - name: product
        in: body
        schema:
          type: object
          properties:
            page:
              type: integer
          required: []
      responses:
        '200':
          description: list of products
  "/api/v1/products":
    get:
      summary: List of products
      tags:
      - Products
      consumes:
      - application/json
      parameters:
      - name: product
        in: body
        schema:
          type: object
          properties:
            page:
              type: integer
          required: []
      responses:
        '200':
          description: list of products
  "/api/v1/products/{id}":
    get:
      summary: Show a products
      tags:
      - Products
      consumes:
      - application/json
      parameters:
      - name: product
        in: body
        schema:
          type: object
          properties:
            id:
              type: integer
          required: []
      responses:
        '200':
          description: product found
        '404':
          description: product not found
